// ═══════════════════════════════════════════════════════════════
//  ImGui IDE (ImGuiColorTextEdit · lobotomy/main) · progress data
//  Source: roadmap.md · README.md · TESTING.md · AUTOMATED_TESTING.md ·
//          PORTABILITY_REVIEW.md · notes-export 2026-05-26
// ═══════════════════════════════════════════════════════════════
window.PROGRESS_DATA = {

  meta: {
    project:     "ImGui IDE",
    version:     "0.9",
    branch:      "lobotomy/main",
    baseline:    "goossens rewrite · v1.92.7-docking fork point",
    repoPath:    "ImGuiColorTextEdit",
    lastUpdated: "2026-05-26",
    docCount:    9,
    sessionId:   "editor IDE build-out · May 2026",
    titlePrefix: "ImGui ",
    titleAccent: "IDE",
    titleSuffix: "",

    tagline:      "A fully featured, multiplatform code editor in C++ with Dear ImGui",
    description:  "A fully featured, multiplatform code editor written in C++ on Dear ImGui — usable as a standalone IDE or an embeddable widget. This fork grew the editor into a real development environment: a docked project tree, project-wide go-to-definition and find-references, word wrap, integrated build & run, an image viewer, multi-window docking, and persistent settings. Forked from ImGuiColorTextEdit, a library with a long development history.",
    featuresAdded: [
      { name: "Project navigation panel",    desc: "A docked file-tree sidebar for the whole project — filter by source files or dotfiles, hover for file info, right-click to open / rename / delete (to Recycle Bin) / copy paths, and drag files to move or copy them." },
      { name: "Go to definition & references",desc: "Right-click any symbol to jump to its definition anywhere in the project, or open a Find References panel grouped by file. Works across multiple files — e.g. a C# class or method used in several places." },
      { name: "Integrated build & run",       desc: "F6 builds the project with the detected toolchain (MSVC / .NET / CMake); F5 runs the built executable, or the active script if there's no build. Output streams into a docked panel." },
      { name: "Word wrap",                    desc: "Toggle soft wrapping so long lines fold to the window width with no horizontal scrolling — caret, selection, and arrow keys all stay correct across wrapped rows." },
      { name: "Image viewer",                 desc: "Open PNG / JPG / BMP / TGA / GIF right inside the editor in a dockable window with zoom, fit, and 1:1 controls — image files in the tree open as images, not garbled text." },
      { name: "Multi-window docking",         desc: "Open files as tabs, then drag any tab out into its own OS window across monitors and dock it back — with keyboard shortcuts to pop out and re-merge documents." },
      { name: "Settings that persist",        desc: "Every preference — word wrap, fonts, pan mode, build config, navigation filters, recent files and projects — saves to disk and restores on next launch, with system-font picking and a keybind catalogue." },
      { name: "Toolchain detection",          desc: "Auto-detects installed Visual Studio (MSVC) and .NET SDKs, exposes a build-config selector (Debug / Release / …), and shows the active toolchain in the status bar for C/C++/C# projects." },
    ],
    bio:          "Senior C++ engineer specializing in game engine tooling, real-time rendering, and immersive experiences. Comfortable owning full technical stacks from engine client through deployment.",
    location:     "Orlando, FL",
    author:       "Logan Brunet",
    role:         "Engines · Graphics · UI / Tools · Offensive Security",
    skills:       ["C++17", "Dear ImGui", "Unreal Engine 4/5", "Lua", "C# / .NET", "GLSL / HLSL", "SDL3", "CMake"],
    linkedIn:     "https://linkedin.com/in/logan-brunet",
    github:       "https://github.com/lobotomy-x",
    repoUrl:      "https://github.com/lobotomy-x/ImGuiColorTextEdit",
    credits: [
      { name: "Balázs Jákó",       handle: "BalazsJako",  role: "original author · 2018",                           url: "https://github.com/BalazsJako/ImGuiColorTextEdit" },
      { name: "Santiago Cubedo",   handle: "santaclose",  role: "220+ commits · most active fork 2019–2023",        url: "https://github.com/santaclose/ImGuiColorTextEdit" },
      { name: "Johan A. Goossens", handle: "goossens",    role: "full rewrite from scratch · current maintainer",   url: "https://github.com/goossens/ImGuiColorTextEdit" },
    ],
    highlights:   ["nav-panel", "go-to-def", "word-wrap", "project-build", "multi-viewport", "image-viewer"],
    impactNumbers: [
      { num: "40+", label: "Features shipped",    sub: "text widget → full IDE" },
      { num: "16",  label: "Languages",           sub: "highlighting + folding" },
      { num: "3×",  label: "Platform support",    sub: "Windows · macOS · Linux" },
    ],
    techStack: [
      "C++17", "Dear ImGui v1.92.7-docking", "SDL3 GPU",
      "CMake", "ImGuiFileDialog", "DTL (BSD)",
      "Multi-viewport docking", "macOS · Linux · Windows",
    ],
    audience: [
      "Standalone desktop IDE on Windows, macOS, and Linux",
      "Or embed the editor widget in any Dear ImGui app — 2-file integration, no platform deps",
      "Portable widget core designed to drop into overlays like ReShade or UEVR",
    ],
    videos: [],
  },

  vitals: {
    shipped:         40,
    inProgress:       2,
    openBugs:         3,
    openFeatures:     4,
    languages:       16,
    filesChanged:     6,
    roundsCompleted:  8,
  },

  // ─────────────────── Cards ───────────────────
  cards: [

    // ── SHIPPED · Navigation Panel ──
    {
      id: "nav-panel",
      title: "Dockable project navigation panel",
      status: "shipped",
      group: "Navigation Panel",
      tags: ["feature", "ide"],
      blurb: "Docked-left file tree of the project root, lazy-expanded per folder. Click to open; the panel is the spine of the IDE shell.",
      detail: "Project root resolves by walking up from the active document to the first .sln / .csproj / .vcxproj / .uproject / CMakeLists.txt / .git marker — the same walker the build system uses.",
      surface: [
        "Header filters: .dot (dotfiles), code (source-only), excl (show excluded), flat (folders only)",
        "Filter defaults persist across runs",
        "Hover a file → tooltip: type, size, created, modified",
        "Lazy directory iteration, cached per node",
      ],
      files: ["example/editor.cpp"],
    },
    {
      id: "nav-file-ops",
      title: "File operations in the tree",
      status: "shipped",
      group: "Navigation Panel",
      tags: ["feature", "ux"],
      blurb: "Right-click: Open, Open in Explorer, Copy path, Copy / Cut / Paste, inline Rename, Delete, Exclude / Re-include.",
      detail: "Delete goes to the Recycle Bin by default (shellapi); a 'Force delete' checkbox does a permanent unlink. All destructive ops confirm.",
      files: ["example/editor.cpp"],
    },
    {
      id: "nav-drag",
      title: "Drag-to-move / copy in the tree",
      status: "shipped",
      group: "Navigation Panel",
      tags: ["feature", "ux"],
      blurb: "Drag a file onto a folder to move it; hold Ctrl to copy. Can't drop a folder into itself. Drag a file into the editor area opens it.",
      files: ["example/editor.cpp"],
    },

    // ── SHIPPED · Symbol Navigation ──
    {
      id: "go-to-def",
      title: "Go to Definition (project-wide)",
      status: "shipped",
      group: "Symbol Navigation",
      tags: ["feature", "ide"],
      blurb: "Right-click a symbol → jump to its definition anywhere in the project. Tested across C# files: classes, methods, interfaces.",
      detail: "Builds on GetWordAt(line, col). Lexical, project-wide scan — no full parser, but resolves the common 'where is this defined' case across files.",
      files: ["example/editor.cpp", "TextEditor.cpp"],
    },
    {
      id: "find-refs",
      title: "Find References panel",
      status: "shipped",
      group: "Symbol Navigation",
      tags: ["feature", "ide"],
      blurb: "Opens a docked panel of every reference to the symbol, grouped by file. Click a hit to open that file at the line.",
      detail: "Project-wide grep keyed on the word under the cursor. Panel docks right alongside the editor area.",
      files: ["example/editor.cpp"],
    },
    {
      id: "get-word-at",
      title: "GetWordAt + word-aware context menu",
      status: "shipped",
      group: "Symbol Navigation",
      tags: ["feature", "api"],
      blurb: "TextEditor::GetWordAt(line, col) → word + Coordinate range, via findWordStart / findWordEnd. Right-click acts on the clicked word without shrinking an existing selection.",
      files: ["TextEditor.cpp", "TextEditor.h"],
    },

    // ── SHIPPED · Editing & View ──
    {
      id: "word-wrap",
      title: "Word wrap",
      status: "shipped",
      group: "Editing & View",
      tags: ["feature", "core"],
      blurb: "Soft wrap to window width — no horizontal scrollbar. Caret, selection, and Up/Down arrows operate row-by-row across wrapped rows.",
      detail: "buildWrapRows() computes row boundaries; mouse hit-testing and cursor movement are wrap-aware. Wrap width slider (0 = fit window). Lives in the portable widget core, off by default.",
      surface: [
        "Click a wrapped line → caret lands on the clicked glyph",
        "Arrow Up/Down moves by visual row, not whole line",
        "Drag-select across wrapped text highlights correctly",
        "v1 gaps (intentional): fold arrows, bracket-match, markers, minimap disabled in wrap mode",
      ],
      files: ["TextEditor.cpp", "TextEditor.h"],
    },
    {
      id: "pan-indicator",
      title: "Pan / scroll indicator",
      status: "shipped",
      group: "Editing & View",
      tags: ["feature", "ux"],
      blurb: "Middle-click-drag shows a ring + arrows indicator at the click point; the arrow toward the drag direction brightens. CAD-style pan, browser-style scroll.",
      detail: "SetShowPanScrollIndicatorEnabled toggles it. SetMiddleMousePanMode / SetMiddleMouseScrollMode switch paradigms; continuous edge-panning accelerates with distance.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "ctrl-scroll-zoom",
      title: "Ctrl + scroll font zoom",
      status: "shipped",
      group: "Editing & View",
      tags: ["feature", "ux"],
      blurb: "Ctrl + mouse wheel zooms the font size live (toggleable in Settings). Uses Dear ImGui v1.92 dynamic font sizing.",
      files: ["example/editor.cpp"],
    },
    {
      id: "minimap",
      title: "Scrollbar minimap",
      status: "shipped",
      group: "Editing & View",
      tags: ["feature"],
      blurb: "Optional minimap renders cursor, selection, and marker locations down the scrollbar lane for at-a-glance document overview.",
      files: ["TextEditor.cpp"],
    },

    // ── SHIPPED · Fold Engine ──
    {
      id: "python-fold",
      title: "Python indent folding",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature", "python"],
      blurb: "Block opens only when indent strictly increases, ends when it decreases. updateVisibility hides [start+1, end] inclusive so the body's last line no longer leaks.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "lua-fold",
      title: "Lua keyword folding",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature", "lua"],
      blurb: "function / if / for / while / do / repeat … end / until fold as blocks. A one-line `if x then y end` correctly does NOT fold.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "ini-fold",
      title: "INI section folding",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature"],
      blurb: "Each [section] folds down to the line before the next header — bracket-header-aware folding driven by the hardcoded INI tokenizer.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-preview",
      title: "Per-type fold previews + AA arrows",
      status: "shipped",
      group: "Fold Engine",
      tags: ["polish", "ux"],
      blurb: 'Indent → " ...", Comment → " /*..*/", IfDef → " #if...", Region → " //...", Braces → " {...}". AA triangle arrows sized to the font.',
      detail: "Single-click a fold preview selects the range; double-click the arrow selects + unfolds. Editing inside a folded region auto-unfolds it.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-all",
      title: "Fold all / Unfold all + comment runs",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature", "keyboard"],
      blurb: "Ctrl+K Ctrl+0 folds all; Ctrl+K Ctrl+J unfolds all. Runs of ≥ 3 single-line-comment lines collapse into a Comment fold.",
      files: ["TextEditor.cpp"],
    },

    // ── SHIPPED · Project & Build ──
    {
      id: "project-open",
      title: "Open project (folder or solution)",
      status: "shipped",
      group: "Project & Build",
      tags: ["feature", "ide"],
      blurb: "Open a folder or a .sln / .csproj / .vcxproj from a CLI arg or the picker. Reopening a project restores the previously open tabs.",
      detail: "Session state persists per project root. example.exe --project <dir> opens the nav panel rooted there with an empty editor area.",
      files: ["example/editor.cpp", "example/main.cpp"],
    },
    {
      id: "project-build",
      title: "Build & run (F5 / F6)",
      status: "shipped",
      group: "Project & Build",
      tags: ["feature", "ide"],
      blurb: "F6 builds via build.bat / CMake / detected toolchain (%CONFIG% expands to the chosen Debug/Release). F5 runs the built exe, else the active script.",
      detail: "Output docks at the bottom with a Copy button. Script fallback dispatches by extension: Python, Lua, PowerShell, Bash, Node, cmd.",
      files: ["example/editor.cpp"],
    },
    {
      id: "toolchains",
      title: "Toolchain detection",
      status: "shipped",
      group: "Project & Build",
      tags: ["feature", "ide"],
      blurb: "Auto-detects MSVC installs and .NET SDKs (dotnet --list-sdks). Build-config combo (Debug/Release/RelWithDebInfo/MinSizeRel) persists.",
      detail: "A status-bar toolchain selector appears for C/C++/C# documents when a project is open.",
      files: ["example/editor.cpp"],
    },

    // ── SHIPPED · Docking & Viewports ──
    {
      id: "multi-viewport",
      title: "Multi-viewport tab docking",
      status: "shipped",
      group: "Docking & Viewports",
      tags: ["feature", "ux"],
      blurb: "Files open as tabs in the central node; drag a tab out to make it its own OS window across monitors, and drop it back to re-dock.",
      detail: "Built on the v1.92.7-docking branch. Popups are routed through SetNextWindowViewport so they land on the correct monitor.",
      files: ["example/editor.cpp", "example/main.cpp"],
    },
    {
      id: "popout-hotkeys",
      title: "Pop-out / merge hotkeys",
      status: "shipped",
      group: "Docking & Viewports",
      tags: ["feature", "keyboard"],
      blurb: "Ctrl+Alt+← / Ctrl+Alt+→ pop the active doc out left/right; Ctrl+Alt+M merges the current doc back, Ctrl+Alt+Shift+M merges all.",
      files: ["example/editor.cpp"],
    },
    {
      id: "reopen-tab",
      title: "Reopen closed tab (Ctrl+Shift+T)",
      status: "shipped",
      group: "Docking & Viewports",
      tags: ["feature", "ux"],
      blurb: "32-deep stack of recently closed tabs. Empty untitled tabs are not pushed. Menu item under File.",
      files: ["example/editor.cpp"],
    },

    // ── SHIPPED · Image Viewer ──
    {
      id: "image-viewer",
      title: "In-editor image viewer",
      status: "shipped",
      group: "Image Viewer",
      tags: ["feature", "graphics"],
      blurb: "PNG / JPG / BMP / TGA / GIF open in a dockable window, auto-fit on open. Zoom slider, 1:1, and Fit; multiple images at once.",
      detail: "stb_image → ImTextureData → RegisterUserTexture against the SDL3 GPU backend — the v1.92 texture path. Binary files with NUL bytes are kept out of the text editor.",
      files: ["example/editor.cpp", "example/main.cpp"],
    },

    // ── SHIPPED · Settings & Persistence ──
    {
      id: "settings-persist",
      title: "Persistent settings",
      status: "shipped",
      group: "Settings & Persistence",
      tags: ["feature", "ide"],
      blurb: "%APPDATA%\\ImGuiColorTextEdit\\settings.txt round-trips every preference: auto-indent, complete-pairs, show-fps, zoom, pan, wrap+width, fps-limit, fonts, nav filters, toolchain, recents.",
      files: ["example/editor.cpp"],
    },
    {
      id: "recents",
      title: "Recent files & projects",
      status: "shipped",
      group: "Settings & Persistence",
      tags: ["feature", "ux"],
      blurb: "Recent Files and Recent Projects menus populate as you work, with dedup + cap and a Clear action. Persisted across runs.",
      files: ["example/editor.cpp"],
    },
    {
      id: "font-selector",
      title: "System font selector",
      status: "shipped",
      group: "Settings & Persistence",
      tags: ["feature", "ux"],
      blurb: "Settings lists installed system fonts and applies the choice live; the selection persists. Built on v1.92 dynamic fonts.",
      files: ["example/editor.cpp"],
    },
    {
      id: "keybinds-ui",
      title: "Keybind catalogue + capture UI",
      status: "shipped",
      group: "Settings & Persistence",
      tags: ["feature", "ux"],
      blurb: "Settings → Keybinds: collapsible groups, click a chord to capture (e.g. Ctrl+Shift+K records cleanly, not 'Ctrl+'). Esc cancels, Backspace clears, reset reverts.",
      detail: "Fixes the reserved-modifier bug (ImGuiKey_ReservedForMod*) so a captured chord serialises correctly. Known gap: captured chords don't yet re-route live actions — catalogue + capture only.",
      files: ["example/editor.cpp"],
    },

    // ── SHIPPED · Languages ──
    {
      id: "ini-lang",
      title: "INI / CFG / CONF highlighting",
      status: "shipped",
      group: "Languages",
      tags: ["feature"],
      blurb: "Hardcoded Language::Ini() tokenizer: [headers] colored, key= keys highlighted, ; and # comments. Drives the INI fold too.",
      files: ["TextEditor.cpp", "TextEditor.h"],
    },
    {
      id: "xaml-lang",
      title: "XAML highlighting",
      status: "shipped",
      group: "Languages",
      tags: ["feature"],
      blurb: ".xaml files get tag / attribute / string highlighting. Listed in the status-bar language dropdown alongside the runtime langs.",
      files: ["example/languages/"],
    },
    {
      id: "runtime-langs",
      title: "Runtime language definitions",
      status: "shipped",
      group: "Languages",
      tags: ["feature", "extensibility"],
      blurb: "Language::FromFile(path) parses key=value .lang files; loadRuntimeLanguages() registers them at startup. HTML, YAML, BAT, PowerShell shipped.",
      detail: "Process-lifetime cache keeps Language pointers stable. Drop any .lang in the languages folder and its declared extensions route automatically after the built-ins.",
      files: ["TextEditor.cpp", "TextEditor.h", "example/languages/"],
    },

    // ── SHIPPED · Library / Integration ──
    {
      id: "autocomplete-trie",
      title: "Autocomplete identifier trie",
      status: "shipped",
      group: "Library / Integration",
      tags: ["feature", "perf"],
      blurb: "buildAutocompleteTrie scans the document into a Trie for context suggestions; Ctrl+Space manual trigger plus type-to-complete, both configurable.",
      files: ["example/editor.cpp", "TextEditor.cpp"],
    },
    {
      id: "header-toggle",
      title: "Header / Source toggle (Alt+O)",
      status: "shipped",
      group: "Library / Integration",
      tags: ["feature", "ide"],
      blurb: "Cycles .h/.hpp/.hxx/.hh ↔ .cpp/.cc/.cxx/.c/.m/.mm/.inl. Re-uses an open tab if present, else opens from disk.",
      files: ["example/editor.cpp"],
    },
    {
      id: "diff-history",
      title: "File history + diff against file",
      status: "shipped",
      group: "Library / Integration",
      tags: ["feature"],
      blurb: "Ctrl+I shows changes since the file was opened with a side-by-side toggle and revert-to-state. 'Diff Against File…' picks a second file and diffs it.",
      detail: "Uses the TextDiff companion widget (DTL-backed). Both diff windows are non-modal and multi-viewport routed.",
      files: ["TextDiff.cpp", "example/editor.cpp"],
    },
    {
      id: "dll-packaging",
      title: "Shared-library packaging",
      status: "shipped",
      group: "Library / Integration",
      tags: ["feature", "build"],
      blurb: "TEXTEDITOR_BUILD_SHARED CMake option builds the editor as a DLL (WINDOWS_EXPORT_ALL_SYMBOLS). Without it, a static lib links into the example.",
      files: ["CMakeLists.txt"],
    },

    // ── SHIPPED · Bug Fixes ──
    {
      id: "fps-throttle",
      title: "FPS idle-throttle fix",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "perf"],
      blurb: "Idle frame-rate throttle (200→10) was firing whenever a popped-out window lost focus, tanking FPS. Now only throttles when the whole app is unfocused.",
      files: ["example/main.cpp"],
    },
    {
      id: "y-scroll-fix",
      title: "Click Y double-scroll fix",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "coordinates"],
      blurb: "mousePos.y was already content-relative; dropped the stray + GetScrollY() that made clicks miss after scrolling.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "scroll-to-fold",
      title: "Scroll-to-bottom on fold-click fix",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "coordinates"],
      blurb: "lineToVisualIndex returned total-visible-count for a hidden line. Fixed by snapping to the nearest visible line at-or-before the target.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "keybind-mod-fix",
      title: "Reserved-modifier chord capture",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix"],
      blurb: "Chord capture recorded garbage (or just 'Ctrl+') for combos using reserved-mod keys. Now Ctrl+Shift+K serialises exactly as typed.",
      files: ["example/editor.cpp"],
    },
    {
      id: "right-edge-padding",
      title: "Right-edge text padding",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "polish"],
      blurb: "Editor text and the TextDiff side-by-side view no longer kiss the vertical scrollbar — added right-edge padding.",
      files: ["TextEditor.cpp", "TextDiff.cpp"],
    },
    {
      id: "subword-params",
      title: "Subword params unified",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "platform"],
      blurb: "Both platforms call moveLeft/moveRight(select, wordMode, subWord) — Ctrl/Cmd = word, Alt = subword. No more macOS/Windows drift.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "sdl3-drop",
      title: "SDL3 drop-event API",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "compatibility"],
      blurb: "SDL_DROPFILE / event.drop.file were SDL2 names; SDL3 uses SDL_EVENT_DROP_FILE / event.drop.data. Example compiles against SDL3.",
      files: ["example/main.cpp"],
    },

    // ── IN PROGRESS ──
    {
      id: "test-infra",
      title: "Automated test harness",
      status: "in-progress",
      group: "Testing & Portability",
      tags: ["testing", "infra"],
      blurb: "Three-tier plan: headless logic tests (fold/wrap/tokenizer math), ImGui Test Engine for UI/docking flows, AI-driven UI smoke pass — all gated behind BUILD_TESTS.",
      detail: "TESTING.md is the manual checklist; AUTOMATED_TESTING.md is the execution plan. Recommendation: headless logic tests first (CI-able), then Test Engine for menu/settings/docking state.",
      surface: [
        "#3 headless: languageForPath, rebuildFoldRanges, buildWrapRows, INI tokenizer, settings round-trip",
        "#2 ImGui Test Engine: word-wrap toggle, dock-node assertions, reset-layout, keybind capture",
        "#1 computer-use agent walks TESTING.md as a pre-release smoke pass",
        "All gated behind option(BUILD_TESTS OFF) so the normal build is unaffected",
      ],
      files: ["AUTOMATED_TESTING.md", "TESTING.md"],
    },
    {
      id: "keybind-reroute",
      title: "Live keybind re-routing",
      status: "in-progress",
      group: "Settings & Persistence",
      tags: ["feature"],
      blurb: "Captured custom chords are catalogued and persisted, but don't yet re-route live actions. Wiring the dispatch table to the captured map is the remaining step.",
      files: ["example/editor.cpp"],
    },
  ],

  // ─────────────────── Open symptoms ───────────────────
  symptoms: [
    {
      id: "cursor-x-bug",
      title: "Cursor X mis-alignment on tab-indented files",
      detail: "Open a .md / tab-indented file, click mid-line — caret can land past the click. Suspected: CalcTextSize('#') called before PushFont so glyphSize.x doesn't match the editor's glyph width, or normalizeCoordinate jumps a tab stop. Fix: assert(column == cursor.column) after a roundtrip.",
      severity: "high",
    },
    {
      id: "wrap-mode-gaps",
      title: "Word-wrap mode feature gaps",
      detail: "In wrap mode, fold arrows, bracket-match highlighting, line markers, and the minimap are intentionally disabled for v1. They should be re-enabled (or gracefully degraded) once the wrap row model is wired into those render passes.",
      severity: "medium",
    },
    {
      id: "keybind-reroute-gap",
      title: "Custom keybinds don't drive actions yet",
      detail: "The keybind UI captures and persists chords but the action dispatch still uses the built-in table. Need to consult the captured map in handleKeyboardInputs before falling back to defaults.",
      severity: "medium",
      kind: "feature",
    },
    {
      id: "docstring-fold-feat",
      title: "/// triple-slash docstring fold",
      detail: "Detect runs of ≥ 3 consecutive /// lines and emit a Comment fold with preview ' ///...', distinct from the generic // comment fold. Wire into rebuildFoldRanges alongside the /* */ handling.",
      severity: "low",
      kind: "feature",
    },
  ],

  // ─────────────────── Fix plan ───────────────────
  plan: [
    {
      step: 1,
      title: "Land the headless test target",
      detail: "Add a --selftest / selftest target (gated behind BUILD_TESTS) exercising the pure logic: languageForPath, rebuildFoldRanges for Lua/INI/Python, buildWrapRows boundaries, INI tokenizer, settings round-trip. Runs in milliseconds, CI-friendly.",
      checks: [
        "buildWrapRows / fold detection callable without a live ImGui context",
        "Known buffers assert expected fold + wrap-row counts",
        "settings.txt write→read round-trips every field",
        "Target builds only under -DBUILD_TESTS=ON",
      ],
      state: "in-progress",
    },
    {
      step: 2,
      title: "Wire ImGui Test Engine UI tests",
      detail: "Fetch imgui_test_engine (tag matching v1.92.7-docking), compile under BUILD_TESTS, extract main.cpp's init/loop into a shared run_frame() helper, and register the first menu/docking/settings tests.",
      checks: [
        "Word-wrap toggle asserts TextEditor::IsWordWrap()",
        "Three open files share one dock node (tabs, not split)",
        "Reset Layout lands Nav / Output / Refs in expected nodes",
        "Keybind capture injects Ctrl+Shift+K and asserts the recorded string",
      ],
      state: "pending",
    },
    {
      step: 3,
      title: "Re-enable wrap-mode features",
      detail: "Teach the fold-arrow, bracket-match, marker, and minimap render passes about the wrap row model so they work with word wrap on instead of being disabled.",
      checks: [
        "Fold arrows render on the correct wrapped row",
        "Bracket-match highlight follows wrapped glyphs",
        "Line markers map to the first visual row of a line",
      ],
      state: "pending",
    },
    {
      step: 4,
      title: "Route captured keybinds to actions",
      detail: "Consult the persisted keybind map in handleKeyboardInputs before the built-in table, so a remapped chord actually fires its action. Keep a reset-to-defaults path.",
      checks: [
        "A remapped chord triggers its action live",
        "Conflicting binds are flagged in the Keybinds UI",
        "Reset reverts to the built-in table",
      ],
      state: "pending",
    },
  ],

  // ─────────────────── Dep-graph edges ───────────────────
  edges: [
    { from: "nav-panel",       to: "nav-file-ops" },
    { from: "nav-panel",       to: "nav-drag" },
    { from: "nav-panel",       to: "project-open" },
    { from: "project-open",    to: "project-build" },
    { from: "project-build",   to: "toolchains" },
    { from: "get-word-at",     to: "go-to-def" },
    { from: "get-word-at",     to: "find-refs" },
    { from: "go-to-def",       to: "project-open" },
    { from: "multi-viewport",  to: "popout-hotkeys" },
    { from: "multi-viewport",  to: "fps-throttle" },
    { from: "nav-file-ops",    to: "image-viewer" },
    { from: "settings-persist",to: "recents" },
    { from: "settings-persist",to: "font-selector" },
    { from: "settings-persist",to: "keybinds-ui" },
    { from: "keybinds-ui",     to: "keybind-reroute" },
    { from: "keybinds-ui",     to: "keybind-mod-fix" },
    { from: "word-wrap",       to: "wrap-mode-gaps" },
    { from: "ini-lang",        to: "ini-fold" },
    { from: "runtime-langs",   to: "xaml-lang" },
    { from: "diff-history",    to: "multi-viewport" },
    { from: "test-infra",      to: "word-wrap" },
    { from: "test-infra",      to: "ini-fold" },
  ],

  // ─────────────────── Language support ───────────────────
  scripts: {
    summary: { builtin: 11, runtime: 5, custom: "∞" },
    rows: [
      { file: "C / C++",       date: "built-in", status: "pass", notes: "Keywords, preprocessor, brace + #if + region + comment folding, bracket matching, GLSL/HLSL variants." },
      { file: "C#",            date: "built-in", status: "pass", notes: "Keywords, string literals, verbatim @\"\", /// XML doc. Go-to-def + find-refs tested across files." },
      { file: "GLSL",          date: "built-in", status: "pass", notes: "Shader keywords, swizzles (.xyz/.rgb), #version preprocessor." },
      { file: "HLSL",          date: "built-in", status: "pass", notes: "DirectX shader keywords, SV_* semantics, cbuffer / tbuffer." },
      { file: "Lua",           date: "built-in", status: "pass", notes: "Keywords, long strings [[...]], --[[ ]] block comments, function/if/for/while/do/repeat folding." },
      { file: "Python",        date: "built-in", status: "pass", notes: "Keywords, strings, indentation-based folding." },
      { file: "SQL",           date: "built-in", status: "pass", notes: "SQL-92 keywords, -- line comments, /* */ blocks." },
      { file: "AngelScript",   date: "built-in", status: "pass", notes: "C-like syntax, engine keywords, // and /* */ comments." },
      { file: "INI / CFG / CONF","date": "built-in", status: "new", notes: "Hardcoded Language::Ini() tokenizer: [headers], key= keys, ; and # comments; section folding." },
      { file: "XAML",          date: "built-in", status: "new",  notes: "Tag / attribute / string highlighting for .xaml; in the status-bar dropdown." },
      { file: "Plain text",    date: "built-in", status: "pass", notes: "No colorizing; URL + file-path detection only." },
      { file: "HTML",          date: "runtime",  status: "pass", notes: "Tags, attributes, string delimiters, <!-- --> comments. html.lang" },
      { file: "YAML",          date: "runtime",  status: "pass", notes: "key: value, block sequences, # comments, strings. yaml.lang" },
      { file: "Batch / CMD",   date: "runtime",  status: "pass", notes: "REM, @ prefix, %VARIABLE% expansion, flow keywords. bat.lang" },
      { file: "PowerShell",    date: "runtime",  status: "pass", notes: "$variables, [TypeName] casts, verb-noun cmdlets, # comments. ps1.lang" },
      { file: "Custom (.lang)","date": "runtime", status: "new", notes: "Drop a key=value .lang in the languages folder — registered at startup via loadRuntimeLanguages()." },
    ],
  },

  // ─────────────────── Files heatmap ───────────────────
  files: [
    {
      path: "example/editor.cpp",
      domain: "example",
      changeCount: 9,
      changes: [
        "Navigation panel: project tree, filters, tooltips, lazy iteration",
        "File ops: rename / delete-to-recycle / exclude / copy-cut-paste / drag move+copy",
        "Symbol nav: Go to Definition + Find References panel (project-wide)",
        "Project sessions: open folder/.sln, restore tabs, --project arg",
        "Build & run: F5 run, F6 build, %CONFIG% expansion, output panel",
        "Toolchains: MSVC + .NET SDK detection, build-config combo, status-bar selector",
        "Docking: multi-viewport tabs, pop-out / merge hotkeys, reset layout",
        "Settings: persistence, recents, font selector, keybind capture UI",
        "Image viewer + autocomplete trie",
      ],
    },
    {
      path: "TextEditor.cpp",
      domain: "core",
      changeCount: 8,
      changes: [
        "Word wrap: buildWrapRows, wrap-aware mouse + cursor, wrap width",
        "Fold engine: Python indent, Lua keyword, INI section, comment runs, previews, AA arrows",
        "Pan/scroll indicator + minimap",
        "GetWordAt / GetCurrentSelectionText",
        "Hardcoded Language::Ini() tokenizer",
        "Coordinate / scroll / fold-click bug fixes",
        "Right-edge padding",
        "Subword movement unified across platforms",
      ],
    },
    {
      path: "TextEditor.h",
      domain: "core",
      changeCount: 4,
      changes: [
        "Word wrap public API (SetWordWrap / SetWrapWidth)",
        "GetWordAt + pan/scroll indicator toggles",
        "Language::Ini() + Language::FromFile() declarations",
        "TEXTEDITOR_API export macro (guarded by TEXTEDITOR_BUILD_SHARED)",
      ],
    },
    {
      path: "TextDiff.cpp",
      domain: "diff",
      changeCount: 2,
      changes: [
        "Side-by-side right-edge padding",
        "Font-push order synced with TextEditor render-loop changes",
      ],
    },
    {
      path: "example/main.cpp",
      domain: "example",
      changeCount: 4,
      changes: [
        "SDL3 GPU backend, multi-viewport enable, popup viewport routing",
        "FPS idle-throttle fix (only throttle when whole app unfocused)",
        "Image texture path: stb_image → ImTextureData → RegisterUserTexture",
        "SDL3 drop-event API rename",
      ],
    },
    {
      path: "CMakeLists.txt",
      domain: "build",
      changeCount: 2,
      changes: [
        "TEXTEDITOR_BUILD_SHARED option (DLL vs static)",
        "BUILD_TESTS option scaffolding (test engine + selftest, gated off)",
      ],
    },
  ],

  // ─────────────────── Side-tasks ───────────────────
  sideTasks: [
    {
      id: "side-portability",
      num: "01",
      title: "Port the widget into overlays (ReShade / UEVR)",
      kind: "rework",
      upstream: "PORTABILITY_REVIEW.md",
      summary: "The portable unit is TextEditor.cpp/.h + TextDiff.cpp/.h + dtl.h (+ .lang files). It pulls only imgui.h, imgui_internal.h, and the C++ STL — no SDL, no Windows.h, no file dialog, no process spawning. All v1.92-era ImGui-isms live in the app shell, not the widget, so the editor can drop into an existing overlay that embeds an older TextEditor.",
      repoPath: "TextEditor.* + TextDiff.* + dtl.h",
      dependsOn: ["word-wrap", "ini-lang", "get-word-at", "dll-packaging"],
      status: "reviewed · port plan documented",
      lastUpdate: "2026-05-26",
      patternsToLift: [
        "Widget-level (travels free): word wrap, folding, Language::Ini(), pan indicator, GetWordAt, TextDiff padding",
        "App-shell (stays in example/): tabs, nav panel, docking, settings, project sessions, go-to-def, dialogs",
        "Platform (per-host re-impl): process spawn, toolchain detect, recycle-bin delete, image viewer, font discovery",
        "Back-port surface for older ImGui is tiny — only font rendering (GetFont / RenderChar) is version-sensitive",
      ],
      actions: [
        { label: "Step 0: identify target app, its ImGui version, and TextEditor lineage", status: "pending" },
        { label: "Drop TextEditor.*/TextDiff.* in; reconcile call sites (additions are opt-in)", status: "pending" },
        { label: "Migrate buildAutocompleteTrie into the widget if the host wants autocomplete", status: "pending" },
        { label: "Re-implement wanted platform features against the host renderer", status: "pending" },
      ],
      acceptance: [
        "Widget compiles against the host's ImGui with only font back-port spots touched",
        "Existing host editor usage keeps working (new APIs default-off)",
        "Folding + word wrap + INI highlighting available in the overlay",
      ],
    },
    {
      id: "side-testing",
      num: "02",
      title: "Stand up the test suite",
      kind: "update",
      upstream: "AUTOMATED_TESTING.md · TESTING.md",
      summary: "Three complementary tiers, none wired up yet: headless logic tests for the wrap/fold/tokenizer math (CI-able), ImGui Test Engine for UI/docking/settings flows, and a computer-use agent walking the manual checklist as a pre-release smoke pass.",
      repoPath: "tests/ (gated behind BUILD_TESTS)",
      dependsOn: ["test-infra", "word-wrap", "ini-fold"],
      status: "planned · execution order set",
      lastUpdate: "2026-05-26",
      actions: [
        { label: "Refactor main.cpp init/loop into a shared run_frame() helper", status: "pending" },
        { label: "Add headless selftest target for fold / wrap / tokenizer math", status: "pending" },
        { label: "Pin an imgui_test_engine tag compatible with v1.92.7-docking", status: "pending" },
        { label: "Resolve headless GPU context for CI (offscreen swapchain / virtual display)", status: "pending" },
      ],
      acceptance: [
        "Headless logic tests run in CI in milliseconds",
        "Test Engine asserts word-wrap, dock-node, reset-layout, keybind-capture flows",
        "TESTING.md checklist passes on Windows + macOS + Linux",
      ],
    },
    {
      id: "side-objecttalk",
      num: "03",
      title: "Sync back to ObjectTalk master",
      kind: "sync",
      upstream: "github.com/goossens/ObjectTalk",
      summary: "This repo is a snapshot of the editor extracted from ObjectTalk. The widget-level changes (word wrap, folding, INI, GetWordAt, pan indicator) need folding back into ObjectTalk's split-source tree at 3rdparty/imguieditor/, with auto-generated files regenerated by the master toolchain.",
      repoPath: "goossens/ObjectTalk / 3rdparty/imguieditor/",
      dependsOn: ["word-wrap", "ini-lang", "get-word-at"],
      status: "pending sync",
      lastUpdate: "2026-05-26",
      actions: [
        { label: "Fold widget-level TextEditor/TextDiff changes into ObjectTalk split sources", status: "pending" },
        { label: "Regenerate auto-generated files via the ObjectTalk toolchain", status: "pending" },
        { label: "Verify ObjectTalk builds clean on macOS, Linux, Windows", status: "pending" },
      ],
      acceptance: [
        "ObjectTalk builds clean on all 3 platforms after sync",
        "Widget-level features available in ObjectTalk's IDE shell",
      ],
    },
  ],

  // ─────────────────── Roadmap milestones ───────────────────
  milestones: [
    { date: "Dec 2024",   label: "Rewrite from scratch by goossens",            kind: "audit" },
    { date: "Q1 2025",    label: "Core: Document / Cursors / Colorizer layers",  kind: "audit" },
    { date: "Apr 2026",   label: "Dear ImGui v1.92.7-docking — fork point",      kind: "ship" },
    { date: "May 10–11",  label: "↳ Logan: fold engine, navigation, runtime langs", kind: "ship" },
    { date: "May 12–20",  label: "↳ Logan: word wrap, nav panel, symbol nav",    kind: "ship" },
    { date: "May 21–26",  label: "↳ Logan: project/build, docking, image viewer, settings", kind: "ship", cardId: "project-build" },
    { date: "→ now",      label: "Test harness + wrap-mode polish",              kind: "in-progress" },
    { date: "→ next",     label: "Live keybind routing · cursor-X fix",          kind: "next" },
    { date: "→ next",     label: "Port widget core into ReShade / UEVR overlays", kind: "next" },
  ],
};
