// ═══════════════════════════════════════════════════════════════
//  ImGuiColorTextEdit · progress data
//  Source: roadmap.md + README.md · sprint 2026-05-10/11
// ═══════════════════════════════════════════════════════════════
window.PROGRESS_DATA = {

  meta: {
    project:     "ImGuiColorTextEdit",
    version:     "0.9",
    branch:      "master",
    baseline:    "santaclose / BalazsJako · 2023 fork",
    repoPath:    "goossens/ImGuiColorTextEdit",
    lastUpdated: "2026-05-11",
    docCount:    7,
    sessionId:   "editor-sprint · 2026-05-10/11 · 5 rounds",
    titlePrefix: "ImGui",
    titleAccent: "ColorText",
    titleSuffix: "Edit",

    tagline:      "Transformed a basic text editor into a fully featured code IDE",
    description:  "ImGui-IDE is a fully featured immediate-mode code editor available as a standalone application comparable to Sublime Text 2 or even VS Code without too many plugins, with support for embedding in other applications with an easy API. The program uses Dear ImGui and is forked from ImGuiColorTextEdit, a library with a long history of development.",
    featuresAdded: [
      { name: "Code folding",                desc: "Collapse any block of code to see just the structure. Works for braces, comments, preprocessor directives, and Python indentation — each with its own visual indicator so you can tell at a glance what's collapsed." },
      { name: "Built-in script runner",      desc: "Press F5 to run the open file directly in Python, Lua, JavaScript, PowerShell, or Bash. Output appears in a docked panel without leaving the editor." },
      { name: "Jump navigation",             desc: "Alt+O switches instantly between a header file and its matching source file. Right-click any #include path to open that file. Reopen recently closed tabs with Ctrl+Shift+T." },
      { name: "VS Code–style shortcuts",     desc: "Chord keyboard shortcuts matching VS Code conventions: fold all, unfold all, uppercase, lowercase. Familiar to any developer who's used a modern editor." },
      { name: "More languages — no rebuild", desc: "14 programming languages supported, up from 8. New languages can be added by dropping a plain-text config file into a folder — no recompilation required." },
      { name: "Drag & drop + file dialogs",  desc: "Drop files directly onto the editor window to open them. The file browser includes a drives sidebar and editable favourites list, matching the feel of a native OS file picker." },
      { name: "Multi-document tabs",         desc: "Edit multiple files at once with full tab management and history. Closed a file by accident? One shortcut brings it back from a 32-tab undo stack." },
      { name: "Context menus",               desc: "Right-click menus on any line or line number, fully customisable by the host application. Supports breakpoint markers, error highlighting, and inline tooltips." },
    ],
    bio:          "Senior C++ engineer specializing in game engine tooling, real-time rendering, and immersive experiences. Comfortable owning full technical stacks from engine client through deployment.",
    location:     "Orlando, FL",
    author:       "Logan Brunet",
    role:         "Game Tools & Modding Engineer",
    skills:       ["C++17", "Dear ImGui", "Unreal Engine 4/5", "Lua", "C# / .NET", "GLSL / HLSL", "SDL3", "CMake"],
    linkedIn:     "https://linkedin.com/in/logan-brunet",
    github:       "https://github.com/lobotomy-x",
    repoUrl:      "https://github.com/lobotomy-x/portfolio",
    credits: [
      { name: "Balázs Jákó",       handle: "BalazsJako",  role: "original author · 2018",                           url: "https://github.com/BalazsJako/ImGuiColorTextEdit" },
      { name: "Santiago Cubedo",   handle: "santaclose",  role: "220+ commits · most active fork 2019–2023",        url: "https://github.com/santaclose/ImGuiColorTextEdit" },
      { name: "Johan A. Goossens", handle: "goossens",    role: "full rewrite from scratch · current maintainer",   url: "https://github.com/goossens/ImGuiColorTextEdit" },
    ],
    highlights:   ["fold-all", "runtime-langs", "chord-shortcuts", "header-toggle", "script-runner", "drag-text"],
    impactNumbers: [
      { num: "22",  label: "Features added",      sub: "code folding, script runner, navigation, file I/O" },
      { num: "14",  label: "Languages supported", sub: "up from 8 — 6 added without a rebuild" },
      { num: "3×",  label: "Platform support",    sub: "Windows · macOS · Linux" },
    ],
    techStack: [
      "C++17", "Dear ImGui v1.92.7", "SDL3",
      "CMake", "ImGuiFileDialog", "DTL (BSD)",
      "DLL / shared lib packaging", "macOS · Linux · Windows",
    ],
    audience: [
      "Standalone desktop IDE on Windows, macOS, and Linux",
      "Or embed it as a library in any C++ application — 2-file integration",
      "Used inside ObjectTalk, a production C++ IDE and scripting environment",
    ],
    videos: [],
  },

  vitals: {
    shipped:         22,
    inProgress:       1,
    openBugs:         2,
    openFeatures:     2,
    languages:       14,
    filesChanged:     8,
    roundsCompleted:  5,
  },

  // ─────────────────── Cards ───────────────────
  cards: [

    // ── SHIPPED · Fold Engine ──
    {
      id: "python-fold",
      title: "Python indent folding rewrite",
      status: "shipped",
      group: "Fold Engine",
      tags: ["bug-fix", "python"],
      blurb: "Block opens only when indent strictly increases, ends when it decreases. Eliminates spurious one-line folds on every top-level statement.",
      detail: "The previous implementation created incorrect fold regions for Python-style indented code. The rewrite properly tracks indent-level transitions to determine block boundaries.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-preview",
      title: "Fold preview indicator per type",
      status: "shipped",
      group: "Fold Engine",
      tags: ["polish", "ux"],
      blurb: 'Indent → " ...", Comment → " /*..*/", IfDef → " #if...", Region → " //...", Braces → " {...}".',
      detail: "Python code no longer shows the braces-style preview. Each fold type has a semantically meaningful indicator that matches the construct being collapsed.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-arrow",
      title: "Fold arrow visual — AA triangles",
      status: "shipped",
      group: "Fold Engine",
      tags: ["polish"],
      blurb: "Anti-aliased triangles sized to the font, nudged right of the line-number gutter. Double-click on the arrow selects the entire fold range.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-all",
      title: "Fold all / Unfold all",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature", "keyboard"],
      blurb: "Ctrl+K Ctrl+0 folds all; Ctrl+K Ctrl+J unfolds all. Wired into the chord shortcut queue and the View menu.",
      detail: "Implements Folder::foldAll(Document&) / unfoldAll(Document&) — each flips every fr.folded flag and calls updateVisibility. Both are also reachable from the chord queue.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-click",
      title: "Click-on-fold-preview select + unfold",
      status: "shipped",
      group: "Fold Engine",
      tags: ["ux"],
      blurb: "Single-click on a fold preview selects the fold range. Double-click also unfolds it.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "docstring-fold",
      title: "// comment runs → Comment fold",
      status: "shipped",
      group: "Fold Engine",
      tags: ["feature"],
      blurb: "rebuildFoldRanges now tracks runs of ≥ 3 consecutive single-line-comment lines. Becomes a Comment fold with preview \" /*..*/\".",
      detail: "Works for any language that defines a singleLineComment marker. Runs of ≥ 3 lines collapse; fewer lines do not. Language-agnostic: C, C++, Lua, SQL, etc. all benefit.",
      files: ["TextEditor.cpp"],
    },

    // ── SHIPPED · Navigation ──
    {
      id: "header-toggle",
      title: "Header / Source toggle (Alt+O)",
      status: "shipped",
      group: "Navigation",
      tags: ["feature", "ide"],
      blurb: "Editor::toggleHeaderSource — cycles .h/.hpp/.hxx/.hh ↔ .cpp/.cc/.cxx/.c. Re-uses an already-open tab if found, otherwise opens from disk.",
      detail: "Uses languageForPath's extension list as source of truth. Alt+O keyboard binding plus File menu entry.",
      files: ["TextEditor.cpp", "TextEditor.h"],
    },
    {
      id: "goto-include",
      title: "#include → Go to File",
      status: "shipped",
      group: "Navigation",
      tags: ["feature", "ide"],
      blurb: 'Context-menu hook detects #include, import, or from lines. Resolves path relative to current document\'s directory. Adds "Go to File" when target exists.',
      files: ["TextEditor.cpp"],
    },
    {
      id: "chord-shortcuts",
      title: "Chord shortcut queue (Ctrl+K prefix)",
      status: "shipped",
      group: "Navigation",
      tags: ["feature", "keyboard"],
      blurb: "Press Ctrl+K to open a prefix; the next key (with Ctrl held) finishes the chord. Releasing Ctrl or Esc cancels.",
      detail: "Built-in chords: Ctrl+K Ctrl+U → uppercase selection, Ctrl+K Ctrl+L → lowercase, Ctrl+K Ctrl+0 → fold all, Ctrl+K Ctrl+J → unfold all.",
      surface: [
        "Ctrl+K Ctrl+U → uppercase selection",
        "Ctrl+K Ctrl+L → lowercase selection",
        "Ctrl+K Ctrl+0 → fold all",
        "Ctrl+K Ctrl+J → unfold all",
      ],
      files: ["TextEditor.cpp"],
    },
    {
      id: "drag-text",
      title: "Click-and-drag selected text",
      status: "shipped",
      group: "Navigation",
      tags: ["feature", "ux"],
      blurb: "Mousedown on an existing selection caches the text + range. Release at a valid drop point moves (plain) or copies (Ctrl). Atomic — single transaction, full undo/redo.",
      detail: "Drops inside the source range are rejected. The move+copy is a single transaction so undo restores both endpoints.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "reopen-tab",
      title: "Ctrl+Shift+T — reopen last tab",
      status: "shipped",
      group: "Navigation",
      tags: ["feature", "ux"],
      blurb: "32-deep stack of recently closed tabs. Empty untitled tabs are not pushed. Menu item under File.",
      files: ["TextEditor.cpp"],
    },

    // ── SHIPPED · Integration ──
    {
      id: "runtime-langs",
      title: "Runtime language definitions",
      status: "shipped",
      group: "Integration",
      tags: ["feature", "extensibility"],
      blurb: "Language::FromFile(path) parses key=value .lang files. Cache is process-lifetime. Six starter language files shipped in example/languages/.",
      detail: "Editor::loadRuntimeLanguages() walks example/languages/ at startup and registers each .lang file's declared extensions, so languageForPath picks them up after built-ins.",
      surface: [
        "HTML (.html, .htm) — tags, attributes, inline JS/CSS",
        "INI / CFG (.ini, .cfg) — sections, key=value, # and ; comments",
        "YAML (.yaml, .yml) — key:value, block sequences, strings",
        "Batch / CMD (.bat, .cmd) — REM, @, %VARIABLE%",
        "PowerShell (.ps1, .psm1) — $variables, cmdlets, [TypeName]",
        "Custom — drop any .lang in example/languages/ for auto-registration",
      ],
      files: ["TextEditor.cpp", "TextEditor.h", "example/languages/"],
    },
    {
      id: "dll-packaging",
      title: "DLL packaging",
      status: "shipped",
      group: "Integration",
      tags: ["feature", "build"],
      blurb: "TEXTEDITOR_BUILD_SHARED CMake option builds TextEditorLib as a DLL via CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS. build.ps1 -Shared flips it.",
      detail: "No manual __declspec(dllexport) annotations required for the first cut. The example continues to link statically — both options coexist via the CMake option.",
      files: ["CMakeLists.txt", "build.ps1"],
    },
    {
      id: "script-runner",
      title: "Script runner (F5)",
      status: "shipped",
      group: "Integration",
      tags: ["feature", "ide"],
      blurb: "F5 saves active doc, picks interpreter from extension (.py→python, .ps1→PowerShell, .bat/.cmd→cmd, .sh→bash, .lua→lua, .js→node), runs with stderr merged.",
      detail: "Output dumped into a dockable 'Output' window. View menu checkbox to show/hide. Per-language interpreter config with sane defaults.",
      files: ["TextEditor.cpp", "example/main.cpp"],
    },
    {
      id: "file-dialog-favs",
      title: "File dialog favourites + drives sidebar",
      status: "shipped",
      group: "Integration",
      tags: ["feature", "ux"],
      blurb: "Switched to ImGuiFileDialog's native Places feature. Drives group + Favourites loaded from .claude/favorites.txt. canEdit=true so users modify in-dialog.",
      detail: "Windows: drives enumerated via GetLogicalDriveStringsW. POSIX: / and $HOME. Both groups registered once on first open.",
      files: ["example/main.cpp"],
    },

    // ── SHIPPED · Bug Fixes ──
    {
      id: "y-scroll-fix",
      title: "Click Y double-scroll fix",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "coordinates"],
      blurb: "mousePos.y was already content-relative; dropped the stray + GetScrollY() that was making clicks miss after scrolling.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "scroll-to-fold",
      title: "Scroll-to-bottom on fold-preview click",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "coordinates"],
      blurb: "lineToVisualIndex returned total-visible-count for a hidden line. Fixed by snapping to the VI of the nearest visible line at-or-before the target.",
      detail: "Root cause: fr.end.line IS hidden with indent folds, so cursor-end's visual index was ≈ total lines → makeCursorVisible scrolled to EOF.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "deindent-fix",
      title: "deindentLines trailing line over-process",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix"],
      blurb: "Loop's lastLine now stops at the previous line when a multi-line selection ends at column 0. Matches what indentLines already did.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "subword-params",
      title: "Subword params unified (macOS / Linux+Win)",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "platform"],
      blurb: "Both platforms now call moveLeft/moveRight(select, wordMode, subWord) with Ctrl/Cmd = word, Alt = subword. Same signature, same semantics, no drift.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "tab-roundtrip",
      title: "Tab → Shift+Tab round-trip",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix"],
      blurb: "Manual cursor->adjustForDelete added to deindentLines. Tab then Shift+Tab now returns cursor to original position.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "fold-on-edit",
      title: "Editing inside folded region auto-unfolds",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "ux"],
      blurb: "Folder::unfoldContaining called from insertText / deleteText when target line is inside a folded region.",
      files: ["TextEditor.cpp"],
    },
    {
      id: "sdl3-drop",
      title: "SDL3 drop event API compat",
      status: "shipped",
      group: "Bug Fixes",
      tags: ["bug-fix", "compatibility"],
      blurb: "SDL_DROPFILE / event.drop.file were SDL2 names; SDL3 uses SDL_EVENT_DROP_FILE / event.drop.data. Example app now compiles against SDL3.",
      files: ["example/main.cpp"],
    },

    // ── IN PROGRESS ──
    {
      id: "docstring-detect",
      title: "/// triple-slash docstring fold",
      status: "in-progress",
      group: "Fold Engine",
      tags: ["feature", "investigate"],
      blurb: "Detect runs of ≥ 3 consecutive /// lines and emit a Comment fold with preview \" ///...\" — distinct from the generic // comment fold (already shipped).",
      detail: "rebuildFoldRanges already handles // comment runs. The /// variant needs a separate pass and a different preview string targeting doc-comment blocks specifically.",
      surface: [
        "2 consecutive /// lines → no fold",
        "3+ consecutive /// lines → Comment fold",
        "Preview shows \" ///...\" (not \" /*..*/\")",
        "Works in C, C++, C#, any language defining ///",
      ],
      files: ["TextEditor.cpp"],
    },
  ],

  // ─────────────────── Open symptoms ───────────────────
  symptoms: [
    {
      id: "cursor-x-bug",
      title: "Cursor X mis-alignment on tab-indented files",
      detail: "Open any .md or tab-indented file, click mid-line — cursor lands visually past the click. Suspected: CalcTextSize('#') called before PushFont so glyphSize.x doesn't match the editor's actual glyph width, or normalizeCoordinate jumps a tab stop. Fix: add assert(column == cursor.column after roundtrip).",
      severity: "high",
    },
    {
      id: "fold-row-bug",
      title: "Fold preview rendered as an extra row",
      detail: "Some configurations render the fold preview indicator on a separate line rather than inline with the collapsed line. May be resolved by the Python indent-fold rewrite — retesting needed with the shipped fixes.",
      severity: "medium",
    },
    {
      id: "word-context-feat",
      title: "Word-based context menu + GetWordAt",
      detail: "Extend SetTextContextMenuCallback with GetWordAt(line, column) → word + Coordinate range. Jump to definition via fast lexical heuristic: scan for TYPENAME word, word(, or define word. Show 'No definition found' otherwise.",
      severity: "medium",
      kind: "feature",
    },
    {
      id: "jump-def-feat",
      title: "Jump to definition (lexical best-effort)",
      detail: "Builds on GetWordAt and the context menu hook. Scans the document for the first occurrence of TYPENAME word, word(, or define word. No real parser required — fast lexical scan. 'No definition found' fallback when scan fails.",
      severity: "low",
      kind: "feature",
    },
  ],

  // ─────────────────── Fix plan ───────────────────
  plan: [
    {
      step: 1,
      title: "Assert cursor X roundtrip",
      detail: "Add assert(column == cursor.column after roundtrip) inside normalizeCoordinate. Open a .md file with mixed tabs, click mid-line, confirm glyphSize.x matches the pushed font size.",
      checks: [
        "CalcTextSize(\"#\") called AFTER PushFont in the render loop",
        "normalizeCoordinate handles all tab widths correctly",
        "Visual column matches cursor.column after roundtrip",
        "assert passes on both .md and .cpp files",
      ],
      state: "pending",
    },
    {
      step: 2,
      title: "Retest fold preview row issue",
      detail: "With the Python indent-fold rewrite shipped, spurious top-level folds causing the extra row may be gone. Open a Python file with 3+ top-level statements and verify inline rendering.",
      checks: [
        "Python file: no extra rows between top-level functions",
        "C++ file: comment-block fold preview is inline",
        "IfDef blocks render ' #if...' preview without extra row",
      ],
      state: "pending",
    },
    {
      step: 3,
      title: "/// triple-slash docstring detection",
      detail: "In rebuildFoldRanges, add a pass for runs of ≥ 3 lines starting with ///. Emit Comment fold with \" ///...\" preview. Wire alongside existing // and /* */ handling.",
      checks: [
        "2 consecutive /// lines: no fold",
        "3+ consecutive /// lines: Comment fold",
        "Preview shows \" ///...\" not \" /*..*/\"",
        "Doesn't interfere with // comment fold in same file",
      ],
      state: "pending",
    },
    {
      step: 4,
      title: "GetWordAt + jump-to-definition",
      detail: "Implement TextEditor::GetWordAt(line, column) via findWordStart / findWordEnd. Wire into SetTextContextMenuCallback. Add lexical jump-to-definition scanning TYPENAME word, word(, define word patterns.",
      checks: [
        "GetWordAt returns correct word at all positions",
        "Context menu shows word at cursor in callback",
        "Jump to definition finds first TYPENAME word occurrence",
        "'No definition found' shown when scan fails",
      ],
      state: "pending",
    },
  ],

  // ─────────────────── Dep-graph edges ───────────────────
  edges: [
    { from: "python-fold",      to: "fold-preview" },
    { from: "docstring-fold",   to: "fold-preview" },
    { from: "fold-preview",     to: "fold-arrow" },
    { from: "fold-preview",     to: "fold-click" },
    { from: "fold-arrow",       to: "fold-all" },
    { from: "chord-shortcuts",  to: "fold-all" },
    { from: "chord-shortcuts",  to: "drag-text" },
    { from: "file-dialog-favs", to: "goto-include" },
    { from: "goto-include",     to: "header-toggle" },
    { from: "runtime-langs",    to: "dll-packaging" },
    { from: "goto-include",     to: "script-runner" },
    { from: "scroll-to-fold",   to: "fold-row-bug" },
    { from: "fold-preview",     to: "fold-row-bug" },
    { from: "y-scroll-fix",     to: "cursor-x-bug" },
    { from: "goto-include",     to: "word-context-feat" },
    { from: "word-context-feat",to: "jump-def-feat" },
  ],

  // ─────────────────── Language support ───────────────────
  scripts: {
    summary: { builtin: 8, runtime: 6, custom: "∞" },
    rows: [
      { file: "C / C++",       date: "built-in", status: "pass", notes: "Full keywords, preprocessor, // and /* */ folding, bracket matching, GLSL/HLSL variants." },
      { file: "C#",            date: "built-in", status: "pass", notes: "Keywords, string literals, verbatim @\"\", XML doc /// comments." },
      { file: "GLSL",          date: "built-in", status: "pass", notes: "Shader keywords, swizzle patterns (.xyz, .rgb), #version preprocessor." },
      { file: "HLSL",          date: "built-in", status: "pass", notes: "DirectX shader keywords, semantics (SV_*), cbuffer/tbuffer." },
      { file: "Lua",           date: "built-in", status: "pass", notes: "Keywords, string delimiters, long strings [[...]], --[[ nested block comments ]]." },
      { file: "SQL",           date: "built-in", status: "pass", notes: "Standard SQL-92 keyword set, -- line comments, /* */ block comments." },
      { file: "AngelScript",   date: "built-in", status: "pass", notes: "C-like syntax, engine-specific keywords, // and /* */ comment styles." },
      { file: "Plain text",    date: "built-in", status: "pass", notes: "No colorizing; URL and file path detection only. Folding disabled." },
      { file: "HTML",          date: "runtime",  status: "new",  notes: "Tag names, attribute keywords, string delimiters, <!-- --> comments. html.lang" },
      { file: "INI / CFG",     date: "runtime",  status: "new",  notes: "[Section] headers, key=value pairs, # and ; line comments. ini.lang + cfg.lang" },
      { file: "YAML",          date: "runtime",  status: "new",  notes: "key: value pairs, block sequences (- item), #  comments, strings. yaml.lang" },
      { file: "Batch / CMD",   date: "runtime",  status: "new",  notes: "REM comments, @ prefix, %VARIABLE% expansion, flow keywords. bat.lang" },
      { file: "PowerShell",    date: "runtime",  status: "new",  notes: "$variables, [TypeName] casts, verb-noun cmdlets, # comments. ps1.lang" },
      { file: "Custom (.lang)","date": "runtime", status: "new", notes: "Drop a key=value .lang in example/languages/ — auto-registered at startup via loadRuntimeLanguages()." },
    ],
  },

  // ─────────────────── Files heatmap ───────────────────
  files: [
    {
      path: "TextEditor.cpp",
      domain: "core",
      changeCount: 7,
      changes: [
        "Fold engine: Python rewrite, previews, AA arrows, fold-all/unfold, click-select, docstring runs",
        "Navigation: chord shortcuts, drag-text, header toggle, go-to-include, Ctrl+Shift+T tab reopen",
        "Bug fixes: Y-scroll, scroll-to-fold coord snap, deindent trailing line, tab round-trip, subword unification",
        "fold-on-edit: Folder::unfoldContaining on insert/delete",
        "Script runner (F5) — interpreter dispatch, dockable output window",
        "Runtime languages: Language::FromFile factory + loadRuntimeLanguages startup walk",
        "File dialog: non-modal, viewport-aware, no viewport pin snap",
      ],
    },
    {
      path: "TextEditor.h",
      domain: "core",
      changeCount: 3,
      changes: [
        "Language::FromFile(path) factory declaration + process-lifetime cache",
        "toggleHeaderSource() public method",
        "TEXTEDITOR_API export macro (guarded by TEXTEDITOR_BUILD_SHARED)",
      ],
    },
    {
      path: "TextDiff.cpp",
      domain: "diff",
      changeCount: 1,
      changes: [
        "Sync glyph-size / font-push order with TextEditor render loop changes",
      ],
    },
    {
      path: "TextDiff.h",
      domain: "diff",
      changeCount: 1,
      changes: [
        "Version bump to match TextEditor.h",
      ],
    },
    {
      path: "CMakeLists.txt",
      domain: "build",
      changeCount: 2,
      changes: [
        "TEXTEDITOR_BUILD_SHARED option — builds TextEditorLib as a shared library",
        "CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS for annotation-free DLL export on Windows",
      ],
    },
    {
      path: "build.ps1",
      domain: "build",
      changeCount: 1,
      changes: [
        "-Shared switch passes -DTEXTEDITOR_BUILD_SHARED=ON to CMake",
      ],
    },
    {
      path: "example/main.cpp",
      domain: "example",
      changeCount: 3,
      changes: [
        "File dialog favourites + drives sidebar (USE_PLACES_FEATURE + PLACES_PANE_DEFAULT_SHOWN)",
        "Script runner output window wiring + View menu show/hide checkbox",
        "SDL3 drop event API rename: SDL_EVENT_DROP_FILE / event.drop.data",
      ],
    },
    {
      path: "example/languages/",
      domain: "langs",
      changeCount: 6,
      changes: [
        "html.lang — HTML/HTM tag and attribute keyword highlighting",
        "ini.lang — INI section headers and key=value pairs",
        "yaml.lang — YAML structure, inline strings, block sequences",
        "cfg.lang — generic config file format",
        "bat.lang — Windows Batch/CMD scripting keywords",
        "ps1.lang — PowerShell $variables and verb-noun cmdlet patterns",
      ],
    },
  ],

  // ─────────────────── Side-tasks ───────────────────
  sideTasks: [
    {
      id: "side-objecttalk",
      num: "01",
      title: "Sync back to ObjectTalk master",
      kind: "sync",
      upstream: "github.com/goossens/ObjectTalk",
      summary: "This repository is a snapshot of the TextEditor code extracted from the ObjectTalk project. All 5 rounds of changes need folding back into ObjectTalk's split-source tree at 3rdparty/imguieditor/, with auto-generated files regenerated by the master toolchain.",
      repoPath: "goossens/ObjectTalk / 3rdparty/imguieditor/",
      dependsOn: ["runtime-langs", "dll-packaging", "header-toggle"],
      status: "pending sync · snapshot up-to-date",
      lastUpdate: "2026-05-11",
      actions: [
        { label: "Fold TextEditor.cpp/h changes back into ObjectTalk split sources", status: "pending" },
        { label: "Regenerate auto-generated files via ObjectTalk toolchain", status: "pending" },
        { label: "Verify ObjectTalk builds clean on macOS, Linux, Windows", status: "pending" },
        { label: "Tag snapshot release as v0.9", status: "pending" },
      ],
      acceptance: [
        "ObjectTalk builds clean on all 3 platforms after sync",
        "All new features accessible from ObjectTalk's IDE shell",
        "Version badge updated to v0.9",
        "CHANGELOG.md entry for May 2026 sprint",
      ],
    },
    {
      id: "side-example",
      num: "02",
      title: "Example application feature coverage",
      kind: "update",
      upstream: "goossens/ImGuiColorTextEdit / example/",
      summary: "The example application needs updating to demonstrate all new features: runtime language loading, script runner output window, file dialog favorites sidebar, header/source toggle, and fold-all / unfold-all controls.",
      repoPath: "example/",
      dependsOn: ["runtime-langs", "script-runner", "file-dialog-favs", "header-toggle", "fold-all"],
      status: "partially updated · 3 items pending",
      lastUpdate: "2026-05-11",
      actions: [
        { label: "Add View menu items for fold all / unfold all", status: "pending" },
        { label: "Wire loadRuntimeLanguages() at startup — main.cpp", status: "done" },
        { label: "Add example showing custom .lang file creation", status: "pending" },
        { label: "Demonstrate chord shortcuts in README example section", status: "pending" },
      ],
      acceptance: [
        "Example builds and runs on macOS, Linux, Windows",
        "All 6 runtime language files load and highlight correctly",
        "Script runner F5 works for .py, .lua, .js, .sh, .ps1, .bat",
        "File dialog shows drives + favourites pane by default",
      ],
    },
    {
      id: "side-docs",
      num: "03",
      title: "Documentation for new features",
      kind: "docs",
      upstream: "goossens/ImGuiColorTextEdit / docs/",
      summary: "New features need documentation: .lang file format spec, DLL CMake options, chord shortcuts keyboard reference, script runner per-language config, and the header/source toggle API.",
      repoPath: "docs/",
      dependsOn: ["runtime-langs", "dll-packaging", "chord-shortcuts", "script-runner"],
      status: "in progress · 1 of 5 pages done",
      lastUpdate: "2026-05-11",
      patternsToLift: [
        "Runtime .lang format: key=value, # comments, extensions= routing, process-lifetime cache",
        "DLL packaging: TEXTEDITOR_BUILD_SHARED option, TEXTEDITOR_API macro usage",
        "Chord shortcuts: Ctrl+K prefix, built-in chords, custom chord registration",
        "Script runner: per-extension interpreter map, output window docking API",
      ],
      actions: [
        { label: "Write docs/runtimeLanguages.md — .lang file format spec", status: "pending" },
        { label: "Update README integration guide with DLL CMake options", status: "pending" },
        { label: "Add chord shortcuts to keyboard reference table in README", status: "pending" },
        { label: "Write docs/scriptRunner.md — interpreter config + output window", status: "pending" },
        { label: "Update docs/autocomplete.md for new Ctrl+Space trigger config", status: "done" },
      ],
    },
  ],

  // ─────────────────── Roadmap milestones ───────────────────
  milestones: [
    { date: "Dec 2024",   label: "Rewrite from scratch by goossens",           kind: "audit" },
    { date: "Q1 2025",    label: "Core: Document / Cursors / Colorizer layers", kind: "audit" },
    { date: "Apr 2026",   label: "Dear ImGui v1.92 + dynamic fonts compat — fork point", kind: "ship" },
    { date: "2026-05-10", label: "↳ Logan: Fold engine overhaul — rounds 1 + 2",  kind: "ship" },
    { date: "2026-05-11", label: "↳ Logan: Nav · DLL · runtime langs · IDE — rounds 3–5", kind: "ship", cardId: "dll-packaging" },
    { date: "→ v0.9",     label: "Snapshot tagged v0.9",                        kind: "in-progress" },
    { date: "→ next",     label: "Cursor X fix · /// docstring detect",         kind: "next" },
    { date: "→ next",     label: "GetWordAt · jump-to-definition",              kind: "next" },
  ],
};
